version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dermanet-postgres
    environment:
      POSTGRES_DB: dermanet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dermanet-network

  redis:
    image: redis:7-alpine
    container_name: dermanet-redis
    ports:
      - "6379:6379"
    networks:
      - dermanet-network

volumes:
  postgres_data:

networks:
  dermanet-network:
    driver: bridge
